name: Deploy to Salesforce

on:
 push:
  branches:
   - main
 
 workflow_dispatch:

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
   - name: checkout to repository
     uses: actions/checkout@v4

   - name: Install sf cli
     run: |
      npm install --global @salesforce/cli
      sf --version
   
   - name: Authenticate with Salesforce
     run: |
      echo ${{secrets.SALESFORCE_AUTH_URL}} > sfdx-auth-url.txt
      sf org login sfdx-url --sfdx-url-file sfdx-auth-url.txt --alias DevHub --set-default

   - name: Deploy to Salesforce
     run: |
      sf project deploy start --source-dir force-app --target-org DevHub --json --loglevel fatal